Hardcode JWT for unauthorized requests
glifio/filecoin-iac pull request #52
Opened 2022-10-17 16:17 UTC by dumikau

2022-10-17 16:20 UTC, ArseniiPetrovich approved these changes
Looks good. 
To be merged and applied _ONLY AFTER 24.10.2022_

2022-10-17 16:51 UTC, witnsby requested changes

2022-10-17 16:51 UTC, witnsby commented on modules/k8s_ingress/kong_crd.tf
> +          var.is_kong_auth_header_block_public_access ? "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJyZWFkIl19.3Yqei1I2T_qS88XZqVNxFbVTxI1AfBJwrpMXnyqSP7E" : "Authorizat
It is not safe. I would like to ask you to keep sensitive data in its current state at least.
Could you follow the existing way to provide sensitive data to the code?

2022-10-17 16:51 UTC, witnsby commented on modules/k8s_ingress/variables.tf
> +  default = true
I know. it is a small thing, but... could you use fmt for the code.
I believe the formatting code can be easy achievable via executing the cli command `terraform fmt`, or via `IDE plugins`.

2022-10-21 13:52 UTC, ArseniiPetrovich approved these changes

2022-10-21 13:53 UTC, witnsby approved these changes

2022-10-21 14:03 UTC, merged