[feature] - Migrate wallaby and callibration to mainnet cluster
glifio/filecoin-iac pull request #79
Opened 2022-11-14 08:55 UTC by dumikau

2022-11-14 09:26 UTC, witnsby commented on k8s/locals.tf
>        "calibration.filecoin.tools",
needs to be careful with applying these changes, because it can affect load balancing.

2022-11-14 09:27 UTC, witnsby approved these changes
looks fine for me

2022-11-14 20:52 UTC, ArseniiPetrovich approved these changes

2022-11-14 20:53 UTC, ArseniiPetrovich requested changes
Well, I think that "is_mainnet" can be _VERY_ misleading in the new context. Should we rename it to "is_dev" and "is_prod"?

2022-11-15 11:31 UTC, ArseniiPetrovich approved these changes

2022-11-16 06:47 UTC, merged